### ISSUE TITLE
Action stopped working

### ISSUE THREAD

**Issue by stephanprantl** [varunsridharan/action-repository-meta#9]
**Describe the bug**
Action doesn't work currently.
I wanted to use it to read REPOSITORY_DESCRIPTION but it seems that currently no variable is filled.

Logs the following when using it:
> Run varunsridharan/action-repository-meta@2.0
  with:
    repository: false
    debug: false
  env:
    GITHUB_TOKEN: ***
(node:2521) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/varunsridharan/action-repository-meta/2.0/webpack:/action-repository-meta/node_modules/@octokit/request/dist-node/index.js:66:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at run (/home/runner/work/_actions/varunsridharan/action-repository-meta/2.0/webpack:/action-repository-meta/src/index.js:16:1)
(node:2521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**To Reproduce**
Used as described in your readme.

Snippet out of my workflow-definition:
> jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read repository metadata
        uses: varunsridharan/action-repository-meta@2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Expected behavior**
Run successfully and fill the variables like described.

**Screenshots**
![image](https://user-images.githubusercontent.com/20207286/107802802-187d0080-6d62-11eb-8b65-0f49218fa0d4.png)

**Additional context**
Found a pretty similar issue: https://github.com/bchr02/node-pre-gyp-github/issues/24
In this issue the github api is different (due to changes maybe).

If this is here also the issue I would suggest to improve the errorhandling so that only single variables aren't filled
when the data can't be gathered.
Also the error shows that node exited with an errorcode != 0 but the step isn't failing (of course you maybe defined it to act like that).

**Comment by varunsridharan** [comment]
Sorry about the delay.

I have added a fix for it. please give it a try and let me know.

**Comment by stephanprantl** [comment]
Thanks a lot!
Current version on main-branch works again.
